package WordUnscramblerApp;


/**
* WordUnscramblerApp/WordUnscrambler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordUnscrambler.idl
* Monday, May 24, 2021 10:20:04 PM SGT
*/

public interface WordUnscrambler extends WordUnscramblerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WordUnscrambler
