package WordUnscramblerApp;


/**
* WordUnscramblerApp/WordUnscramblerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordUnscrambler.idl
* Thursday, May 13, 2021 12:04:40 AM SGT
*/

public interface WordUnscramblerOperations 
{
  void registerPlayer (String player);
  boolean checkIfActive (String player);
  String getRandWord ();
  String shuffleLetters (String mysteryWord);
  boolean checkAnswer (String guessWord);
  String requestShuffle (String w);
} // interface WordUnscramblerOperations
