package WordUnscramblerApp;


/**
* WordUnscramblerApp/WordUnscramblerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordUnscrambler.idl
* Monday, May 24, 2021 10:20:04 PM SGT
*/

public interface WordUnscramblerOperations 
{
  boolean registerPlayer (String player);
  String getShuffledMysteryWord (String player);
  String shuffleLetters (String player, String mysteryWord);
  boolean checkAnswer (String player, String guessWord);
  boolean removePlayer (String player);
  String answer (String player);
} // interface WordUnscramblerOperations
