# DO NOT EDIT THIS FILE!
#
# Python module WordUnscramblerApp__POA generated by omniidl

import omniORB
omniORB.updateModule("WordUnscramblerApp__POA")

# ** 1. Stub files contributing to this module
import WordUnscrambler_idl

# ** 2. Sub-modules

# ** 3. End
