package WordUnscramblerApp;


/**
* WordUnscramblerApp/WordUnscrambler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordUnscrambler.idl
* Wednesday, May 12, 2021 6:01:07 PM SGT
*/

public interface WordUnscrambler extends WordUnscramblerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WordUnscrambler
